# Generated by Django 5.1 on 2024-09-10 08:39

import sorl.thumbnail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=sorl.thumbnail.fields.ImageField(default='', upload_to=''),
        ),
        migrations.AddField(
            model_name='post',
            name='summary',
            field=models.TextField(default=''),
        ),
    ]
