# Generated by Django 5.1 on 2024-09-10 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0007_alter_post_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
    ]
