# Generated by Django 5.1 on 2024-09-11 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0013_alter_post_likes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='likes',
            new_name='numberlikes',
        ),
    ]
