# Generated by Django 5.1 on 2024-09-11 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0014_rename_likes_post_numberlikes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='numberlikes',
        ),
        migrations.AddField(
            model_name='post',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
