# Generated by Django 5.1 on 2024-09-12 21:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0017_remove_comment_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 12, 22, 28, 23, 310533)),
        ),
    ]
